/**
 * Shared template fragments used by multiple generators.
 * SQL migration pieces, TS import blocks, and test setup boilerplate.
 */

import { toPascalCase, toCamelCase, toKebabCase } from "./naming.js";

export function migrationHeader(tableName: string): string {
  return `-- Migration: Create ${tableName} table
-- Auto-generated by gen:migration — fill in TODO sections
--
-- Conventions:
--   snake_case for all columns and table names
--   tenant_id on every table (multi-tenant isolation)
--   id UUID with gen_random_uuid()
--   created_at / updated_at timestamps on every table
`;
}

export function standardColumns(): string {
  return `  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id),
  -- TODO: Add table-specific columns here
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()`;
}

export function rlsPolicy(tableName: string): string {
  return `-- Enable Row-Level Security
ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;

-- Tenant isolation policy
CREATE POLICY tenant_isolation_${tableName} ON ${tableName}
  USING (tenant_id = current_setting('app.current_tenant_id')::UUID)
  WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::UUID);`;
}

export function updatedAtTrigger(tableName: string): string {
  return `-- Auto-update updated_at timestamp
CREATE TRIGGER set_updated_at_${tableName}
  BEFORE UPDATE ON ${tableName}
  FOR EACH ROW
  EXECUTE FUNCTION trigger_set_updated_at();`;
}

export function tenantIdIndex(tableName: string): string {
  return `CREATE INDEX idx_${tableName}_tenant_id ON ${tableName}(tenant_id);`;
}

export function importBlock(
  type: "routes" | "service" | "repository" | "schema" | "types",
  moduleName: string,
): string {
  const pascal = toPascalCase(moduleName);
  const camel = toCamelCase(moduleName);
  const kebab = toKebabCase(moduleName);

  switch (type) {
    case "routes":
      return `import { Router } from 'express';
import { authenticate } from '@/middleware/authenticate';
import { authorize } from '@/middleware/authorize';
import { validate } from '@/middleware/validate';
import { ${camel}Schema } from './${kebab}.schema';
import { ${pascal}Service } from './${kebab}.service';`;

    case "service":
      return `import { ${pascal}Repository } from './${kebab}.repository';
import type { Create${pascal}Dto, Update${pascal}Dto, ${pascal}, ${pascal}ListParams } from './${kebab}.types';`;

    case "repository":
      return `import { BaseRepository } from '@/db/base-repository';
import type { ${pascal} } from './${kebab}.types';`;

    case "schema":
      return `import { z } from 'zod';`;

    case "types":
      return ``;
  }
}

export function testSetup(): string {
  return `import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { createTestTenant, createTestUser, getAuthToken, resetDatabase } from '@/test/utils';`;
}

export function unitTestSetup(moduleName: string): string {
  const pascal = toPascalCase(moduleName);
  const kebab = toKebabCase(moduleName);

  return `import { describe, it, expect, beforeEach, vi } from 'vitest';
import { ${pascal}Service } from '../${kebab}.service';
import { ${pascal}Repository } from '../${kebab}.repository';

vi.mock('../${kebab}.repository');`;
}

export function integrationTestSetup(moduleName: string): string {
  const kebab = toKebabCase(moduleName);

  return `import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import request from 'supertest';
import { app } from '@/app';
import { createTestTenant, createTestUser, getAuthToken, resetDatabase } from '@/test/utils';`;
}
