/**
 * Generate seed data files with multi-tenant structure.
 * Usage: pnpm gen:seed <table_name|all>
 */

import * as path from "node:path";
import { parseArgs, validateArgs, type CliConfig } from "./lib/cli.js";
import {
  toSnakeCase,
  toTableName,
  toPascalCase,
  toCamelCase,
} from "./lib/naming.js";
import { writeFile, reportCreatedFiles } from "./lib/writer.js";

const config: CliConfig = {
  scriptName: "seed",
  description: "Generate tenant-aware seed data for testing and development",
  args: [
    {
      name: "table_name",
      description: 'Table name or "all" for master runner',
      required: true,
    },
  ],
  examples: [
    "pnpm gen:seed cone_purchases",
    "pnpm gen:seed products",
    "pnpm gen:seed all",
  ],
};

const parsed = parseArgs(config);
const [rawName] = validateArgs(parsed, config);

if (rawName === "all") {
  generateMasterRunner();
} else {
  generateTableSeed(rawName);
}

reportCreatedFiles();

function generateTableSeed(name: string): void {
  const tableName = toTableName(name);
  const pascal = toPascalCase(name);
  const camel = toCamelCase(name);

  const filePath = path.resolve("src/db/seeds", `${tableName}.seed.ts`);

  const content = `/**
 * Seed data for ${tableName}
 * Auto-generated by gen:seed — fill in TODO sections with realistic domain data
 */

import type { Knex } from 'knex';

// Test tenant IDs — use these consistently across all seed files
const TENANT_1 = '11111111-1111-1111-1111-111111111111'; // Primary test tenant
const TENANT_2 = '22222222-2222-2222-2222-222222222222'; // Secondary tenant (isolation testing)

// FK Dependencies:
// TODO: List tables this seed depends on (must be seeded first)
// e.g., tenants, godowns, products

export async function seed(knex: Knex): Promise<void> {
  // Clear existing seed data (in reverse FK order)
  await knex('${tableName}').whereIn('tenant_id', [TENANT_1, TENANT_2]).del();

  // --- Tenant 1: Primary test data ---
  const tenant1${pascal}: Array<Record<string, unknown>> = [
    {
      tenant_id: TENANT_1,
      // TODO: Add realistic domain data fields
      // Reference: docs/powerloom-erp-v3.md for field definitions
    },
    // TODO: Add more rows covering:
    //   - Happy path scenario
    //   - Edge cases (zero quantities, max values)
    //   - All relevant ENUM states
  ];

  // --- Tenant 2: Isolation verification data ---
  const tenant2${pascal}: Array<Record<string, unknown>> = [
    {
      tenant_id: TENANT_2,
      // TODO: Add minimal data to verify tenant isolation
      // This data should NEVER appear in Tenant 1 queries
    },
  ];

  await knex('${tableName}').insert([...tenant1${pascal}, ...tenant2${pascal}]);

  console.log(\`  Seeded \${tenant1${pascal}.length + tenant2${pascal}.length} rows in ${tableName}\`);
}
`;

  writeFile(filePath, content);
}

function generateMasterRunner(): void {
  const filePath = path.resolve("src/db/seeds", "index.seed.ts");

  const content = `/**
 * Master seed runner — executes all seeds in FK dependency order.
 * Auto-generated by gen:seed all
 */

import type { Knex } from 'knex';

// Import seed functions in FK dependency order
// TODO: Add imports as seed files are created
// import { seed as seedTenants } from './tenants.seed';
// import { seed as seedGodowns } from './godowns.seed';
// import { seed as seedProducts } from './products.seed';
// import { seed as seedConePurchases } from './cone_purchases.seed';

// FK dependency order (seed in this order, truncate in reverse)
const SEED_ORDER = [
  // TODO: List seed functions in FK dependency order
  // Level 0: No dependencies
  // seedTenants,

  // Level 1: Depends on tenants only
  // seedGodowns,
  // seedProducts,
  // seedSuppliers,
  // seedCustomers,

  // Level 2: Depends on Level 1
  // seedConePurchases,
  // seedPaavuPreparations,
  // seedWagerAssignments,

  // Level 3: Depends on Level 2
  // seedWagerReturns,
  // seedDamageRecords,

  // Level 4: Depends on Level 3
  // seedInvoices,
  // seedPayments,
] as const;

export async function seedAll(knex: Knex): Promise<void> {
  console.log('Starting seed...');

  for (const seedFn of SEED_ORDER) {
    // @ts-expect-error — uncomment seeds above to resolve
    await seedFn(knex);
  }

  console.log('\\nAll seeds complete!');
}
`;

  writeFile(filePath, content);
}
