/**
 * Generate a single API endpoint snippet for an existing module.
 * Usage: pnpm gen:endpoint <METHOD> </api/path> <module_name>
 */

import * as path from "node:path";
import { parseArgs, validateArgs, type CliConfig } from "./lib/cli.js";
import {
  toKebabCase,
  toPascalCase,
  toCamelCase,
  toSnakeCase,
} from "./lib/naming.js";
import { writeFile, reportCreatedFiles } from "./lib/writer.js";

const VALID_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"] as const;

const config: CliConfig = {
  scriptName: "endpoint",
  description:
    "Generate a single API endpoint snippet to paste into an existing module",
  args: [
    {
      name: "method",
      description: `HTTP method (${VALID_METHODS.join("|")})`,
      required: true,
    },
    {
      name: "path",
      description: "API path (e.g., /api/cone-purchases/:id/approve)",
      required: true,
    },
    { name: "module_name", description: "Target module name", required: true },
  ],
  examples: [
    "pnpm gen:endpoint POST /api/cone-purchases cone-purchase",
    "pnpm gen:endpoint GET /api/wager-returns/:wagerId wager-return",
    "pnpm gen:endpoint PUT /api/damages/:id/approve damage",
  ],
};

const parsed = parseArgs(config);
const [rawMethod, apiPath, rawModule] = validateArgs(parsed, config);

const method = rawMethod.toUpperCase();
if (!VALID_METHODS.includes(method as any)) {
  console.error(
    `Invalid method: ${method}. Must be one of: ${VALID_METHODS.join(", ")}`,
  );
  process.exit(1);
}

const kebab = toKebabCase(rawModule);
const pascal = toPascalCase(rawModule);
const camel = toCamelCase(rawModule);
const snake = toSnakeCase(rawModule);

// Derive operation name from path and method
const pathSegments = apiPath.split("/").filter((s) => s && !s.startsWith(":"));
const lastSegment = pathSegments[pathSegments.length - 1];
const operationName = lastSegment
  ? toCamelCase(`${method.toLowerCase()}_${lastSegment}`)
  : toCamelCase(`${method.toLowerCase()}_${rawModule}`);

const pascalOperation = toPascalCase(operationName);

// Create snippet file
const safePathName = apiPath.replace(/[/:]/g, "-").replace(/^-+|-+$/g, "");
const snippetFile = `${method.toLowerCase()}-${safePathName}.snippet.ts`;
const snippetPath = path.resolve(
  "src/modules",
  kebab,
  "_generated",
  snippetFile,
);

const content = `/**
 * Endpoint snippet: ${method} ${apiPath}
 * Auto-generated by gen:endpoint — paste sections into existing module files
 *
 * Module: ${kebab}
 */

// ============================================================
// --- PASTE INTO: ${kebab}.routes.ts ---
// ============================================================

// ${method} ${apiPath}
router.${method.toLowerCase()}(
  '${apiPath.replace(/^\/api\/[^/]+/, "")}',
  authenticate,
  authorize('${snake}:${method === "GET" ? "read" : "write"}'),${method !== "GET" && method !== "DELETE" ? `\n  validate(${camel}Schema.${operationName}),` : ""}
  async (req, res, next) => {
    try {
      ${buildRouteBody(method, apiPath)}
    } catch (err) {
      next(err);
    }
  }
);

// ============================================================
// --- PASTE INTO: ${kebab}.schema.ts ---
// ============================================================

${buildSchemaSnippet(method, operationName, pascal)}

// ============================================================
// --- PASTE INTO: ${kebab}.service.ts ---
// ============================================================

async ${operationName}(tenantId: string${buildServiceParams(method, apiPath)}): Promise<${buildServiceReturn(method, pascal)}> {
  // TODO: Implement business logic
  ${buildServiceBody(method, apiPath, pascal)}
}

// ============================================================
// --- ADD TO: ${kebab}.service.test.ts ---
// ============================================================

describe('${operationName}', () => {
  it('should ${describeOperation(method, apiPath)}', async () => {
    // TODO: Arrange
    // TODO: Act
    // TODO: Assert
    expect(true).toBe(true);
  });

  it('should enforce tenant isolation', async () => {
    // TODO: Verify tenant scoping
    expect(true).toBe(true);
  });

  // TODO: Add edge case tests
});

// ============================================================
// --- ADD TO: ${kebab}.api.test.ts ---
// ============================================================

describe('${method} ${apiPath}', () => {
  it('should return 401 without auth', async () => {
    const res = await request(app)
      .${method.toLowerCase()}('${apiPath}')
      .send(${method === "GET" || method === "DELETE" ? "" : "{}"});
    expect(res.status).toBe(401);
  });
${
  method !== "GET" && method !== "DELETE"
    ? `
  it('should return 400 with invalid body', async () => {
    const res = await request(app)
      .${method.toLowerCase()}('${apiPath}')
      .set('Authorization', \`Bearer \${tenant1Token}\`)
      .send({});
    expect(res.status).toBe(400);
  });
`
    : ""
}
  it('should return ${method === "POST" ? "201" : "200"} on success', async () => {
    const res = await request(app)
      .${method.toLowerCase()}('${apiPath}')
      .set('Authorization', \`Bearer \${tenant1Token}\`)${method !== "GET" && method !== "DELETE" ? `\n      .send({\n        // TODO: Add valid request body\n      })` : ""};
    expect(res.status).toBe(${method === "POST" ? "201" : method === "DELETE" ? "204" : "200"});
  });
});
`;

writeFile(snippetPath, content);
reportCreatedFiles();

// --- Helper functions ---

function buildRouteBody(method: string, apiPath: string): string {
  const hasIdParam = apiPath.includes(":id");

  if (method === "GET" && !hasIdParam) {
    return `const result = await service.${operationName}(req.tenantId, req.query);
      res.json(result);`;
  }
  if (method === "GET" && hasIdParam) {
    return `const result = await service.${operationName}(req.tenantId, req.params.id);
      res.json(result);`;
  }
  if (method === "POST") {
    return `const result = await service.${operationName}(req.tenantId, req.body);
      res.status(201).json(result);`;
  }
  if (method === "PUT" || method === "PATCH") {
    return `const result = await service.${operationName}(req.tenantId, req.params.id, req.body);
      res.json(result);`;
  }
  if (method === "DELETE") {
    return `await service.${operationName}(req.tenantId, req.params.id);
      res.status(204).send();`;
  }
  return `// TODO: Implement route handler`;
}

function buildSchemaSnippet(
  method: string,
  opName: string,
  pascal: string,
): string {
  if (method === "GET" || method === "DELETE") {
    return `// No request body schema needed for ${method}`;
  }
  return `const ${opName}Schema = z.object({
  // TODO: Add request body fields
  // field: z.string().min(1),
});

export type ${toPascalCase(opName)}Input = z.infer<typeof ${opName}Schema>;

// Add to schema export object:
// ${opName}: ${opName}Schema,`;
}

function buildServiceParams(method: string, apiPath: string): string {
  const hasId = apiPath.includes(":id");
  if (method === "GET" && !hasId) return ", params: any";
  if (method === "GET" && hasId) return ", id: string";
  if (method === "POST") return ", dto: any";
  if (method === "PUT" || method === "PATCH") return ", id: string, dto: any";
  if (method === "DELETE") return ", id: string";
  return "";
}

function buildServiceReturn(method: string, pascal: string): string {
  if (method === "DELETE") return "void";
  return pascal;
}

function buildServiceBody(
  method: string,
  apiPath: string,
  pascal: string,
): string {
  if (method === "DELETE") return `await this.repo.delete(tenantId, id);`;
  return `// TODO: Implement\n  throw new Error('Not implemented');`;
}

function describeOperation(method: string, apiPath: string): string {
  const lastSeg = apiPath.split("/").filter(Boolean).pop() || "";
  if (method === "GET") return `retrieve ${lastSeg.replace(/:/, "")}`;
  if (method === "POST") return `create a new record`;
  if (method === "PUT" || method === "PATCH") return `update the record`;
  if (method === "DELETE") return `delete the record`;
  return `handle ${method} ${apiPath}`;
}
